platform :ios, '7.0'

target 'LWAlipaySDK' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  pod 'LWAlipaySDK', :path => '../'
  

end
